-- Migration: Create tasks table
-- Tasks are extracted from journal messages by AI and managed by the user.
-- category: 'must-do' | 'maybe' | 'backlog'
-- status:   'open' | 'done' | 'removed'
-- tags:     comma-separated list generated by AI, e.g. "work,personal"

CREATE TABLE IF NOT EXISTS tasks (
  id          INTEGER PRIMARY KEY AUTOINCREMENT,
  title       TEXT    NOT NULL,
  notes       TEXT    NOT NULL DEFAULT '',
  category    TEXT    NOT NULL DEFAULT 'maybe' CHECK(category IN ('must-do', 'maybe', 'backlog')),
  status      TEXT    NOT NULL DEFAULT 'open'  CHECK(status   IN ('open', 'done', 'removed')),
  tags        TEXT    NOT NULL DEFAULT '',
  estimate_minutes INTEGER,
  due_date    TEXT,
  created_at  TEXT    NOT NULL DEFAULT (datetime('now')),
  updated_at  TEXT    NOT NULL DEFAULT (datetime('now')),
  source_date TEXT                               -- journal date the task was extracted from
);

CREATE INDEX idx_tasks_status   ON tasks(status);
CREATE INDEX idx_tasks_category ON tasks(category);
CREATE INDEX idx_tasks_due_date ON tasks(due_date);
